/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gossiperl.client.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DigestSubscriptions implements org.apache.thrift.TBase<DigestSubscriptions, DigestSubscriptions._Fields>, java.io.Serializable, Cloneable, Comparable<DigestSubscriptions> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DigestSubscriptions");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField HEARTBEAT_FIELD_DESC = new org.apache.thrift.protocol.TField("heartbeat", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField REPLY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("reply_id", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField SUBSCRIPTIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("subscriptions", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DigestSubscriptionsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DigestSubscriptionsTupleSchemeFactory());
  }

  public String name; // required
  public long heartbeat; // required
  public String reply_id; // required
  public List<DigestSubscription> subscriptions; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    HEARTBEAT((short)2, "heartbeat"),
    REPLY_ID((short)3, "reply_id"),
    SUBSCRIPTIONS((short)4, "subscriptions");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // HEARTBEAT
          return HEARTBEAT;
        case 3: // REPLY_ID
          return REPLY_ID;
        case 4: // SUBSCRIPTIONS
          return SUBSCRIPTIONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HEARTBEAT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HEARTBEAT, new org.apache.thrift.meta_data.FieldMetaData("heartbeat", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.REPLY_ID, new org.apache.thrift.meta_data.FieldMetaData("reply_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SUBSCRIPTIONS, new org.apache.thrift.meta_data.FieldMetaData("subscriptions", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DigestSubscription.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DigestSubscriptions.class, metaDataMap);
  }

  public DigestSubscriptions() {
  }

  public DigestSubscriptions(
    String name,
    long heartbeat,
    String reply_id,
    List<DigestSubscription> subscriptions)
  {
    this();
    this.name = name;
    this.heartbeat = heartbeat;
    setHeartbeatIsSet(true);
    this.reply_id = reply_id;
    this.subscriptions = subscriptions;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DigestSubscriptions(DigestSubscriptions other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetName()) {
      this.name = other.name;
    }
    this.heartbeat = other.heartbeat;
    if (other.isSetReply_id()) {
      this.reply_id = other.reply_id;
    }
    if (other.isSetSubscriptions()) {
      List<DigestSubscription> __this__subscriptions = new ArrayList<DigestSubscription>(other.subscriptions.size());
      for (DigestSubscription other_element : other.subscriptions) {
        __this__subscriptions.add(new DigestSubscription(other_element));
      }
      this.subscriptions = __this__subscriptions;
    }
  }

  public DigestSubscriptions deepCopy() {
    return new DigestSubscriptions(this);
  }

  @Override
  public void clear() {
    this.name = null;
    setHeartbeatIsSet(false);
    this.heartbeat = 0;
    this.reply_id = null;
    this.subscriptions = null;
  }

  public String getName() {
    return this.name;
  }

  public DigestSubscriptions setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public long getHeartbeat() {
    return this.heartbeat;
  }

  public DigestSubscriptions setHeartbeat(long heartbeat) {
    this.heartbeat = heartbeat;
    setHeartbeatIsSet(true);
    return this;
  }

  public void unsetHeartbeat() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HEARTBEAT_ISSET_ID);
  }

  /** Returns true if field heartbeat is set (has been assigned a value) and false otherwise */
  public boolean isSetHeartbeat() {
    return EncodingUtils.testBit(__isset_bitfield, __HEARTBEAT_ISSET_ID);
  }

  public void setHeartbeatIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HEARTBEAT_ISSET_ID, value);
  }

  public String getReply_id() {
    return this.reply_id;
  }

  public DigestSubscriptions setReply_id(String reply_id) {
    this.reply_id = reply_id;
    return this;
  }

  public void unsetReply_id() {
    this.reply_id = null;
  }

  /** Returns true if field reply_id is set (has been assigned a value) and false otherwise */
  public boolean isSetReply_id() {
    return this.reply_id != null;
  }

  public void setReply_idIsSet(boolean value) {
    if (!value) {
      this.reply_id = null;
    }
  }

  public int getSubscriptionsSize() {
    return (this.subscriptions == null) ? 0 : this.subscriptions.size();
  }

  public java.util.Iterator<DigestSubscription> getSubscriptionsIterator() {
    return (this.subscriptions == null) ? null : this.subscriptions.iterator();
  }

  public void addToSubscriptions(DigestSubscription elem) {
    if (this.subscriptions == null) {
      this.subscriptions = new ArrayList<DigestSubscription>();
    }
    this.subscriptions.add(elem);
  }

  public List<DigestSubscription> getSubscriptions() {
    return this.subscriptions;
  }

  public DigestSubscriptions setSubscriptions(List<DigestSubscription> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public void unsetSubscriptions() {
    this.subscriptions = null;
  }

  /** Returns true if field subscriptions is set (has been assigned a value) and false otherwise */
  public boolean isSetSubscriptions() {
    return this.subscriptions != null;
  }

  public void setSubscriptionsIsSet(boolean value) {
    if (!value) {
      this.subscriptions = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case HEARTBEAT:
      if (value == null) {
        unsetHeartbeat();
      } else {
        setHeartbeat((Long)value);
      }
      break;

    case REPLY_ID:
      if (value == null) {
        unsetReply_id();
      } else {
        setReply_id((String)value);
      }
      break;

    case SUBSCRIPTIONS:
      if (value == null) {
        unsetSubscriptions();
      } else {
        setSubscriptions((List<DigestSubscription>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case HEARTBEAT:
      return Long.valueOf(getHeartbeat());

    case REPLY_ID:
      return getReply_id();

    case SUBSCRIPTIONS:
      return getSubscriptions();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case HEARTBEAT:
      return isSetHeartbeat();
    case REPLY_ID:
      return isSetReply_id();
    case SUBSCRIPTIONS:
      return isSetSubscriptions();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DigestSubscriptions)
      return this.equals((DigestSubscriptions)that);
    return false;
  }

  public boolean equals(DigestSubscriptions that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_heartbeat = true;
    boolean that_present_heartbeat = true;
    if (this_present_heartbeat || that_present_heartbeat) {
      if (!(this_present_heartbeat && that_present_heartbeat))
        return false;
      if (this.heartbeat != that.heartbeat)
        return false;
    }

    boolean this_present_reply_id = true && this.isSetReply_id();
    boolean that_present_reply_id = true && that.isSetReply_id();
    if (this_present_reply_id || that_present_reply_id) {
      if (!(this_present_reply_id && that_present_reply_id))
        return false;
      if (!this.reply_id.equals(that.reply_id))
        return false;
    }

    boolean this_present_subscriptions = true && this.isSetSubscriptions();
    boolean that_present_subscriptions = true && that.isSetSubscriptions();
    if (this_present_subscriptions || that_present_subscriptions) {
      if (!(this_present_subscriptions && that_present_subscriptions))
        return false;
      if (!this.subscriptions.equals(that.subscriptions))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(DigestSubscriptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHeartbeat()).compareTo(other.isSetHeartbeat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHeartbeat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.heartbeat, other.heartbeat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReply_id()).compareTo(other.isSetReply_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReply_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reply_id, other.reply_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSubscriptions()).compareTo(other.isSetSubscriptions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubscriptions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subscriptions, other.subscriptions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DigestSubscriptions(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("heartbeat:");
    sb.append(this.heartbeat);
    first = false;
    if (!first) sb.append(", ");
    sb.append("reply_id:");
    if (this.reply_id == null) {
      sb.append("null");
    } else {
      sb.append(this.reply_id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("subscriptions:");
    if (this.subscriptions == null) {
      sb.append("null");
    } else {
      sb.append(this.subscriptions);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'name' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'heartbeat' because it's a primitive and you chose the non-beans generator.
    if (reply_id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'reply_id' was not present! Struct: " + toString());
    }
    if (subscriptions == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'subscriptions' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DigestSubscriptionsStandardSchemeFactory implements SchemeFactory {
    public DigestSubscriptionsStandardScheme getScheme() {
      return new DigestSubscriptionsStandardScheme();
    }
  }

  private static class DigestSubscriptionsStandardScheme extends StandardScheme<DigestSubscriptions> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DigestSubscriptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HEARTBEAT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.heartbeat = iprot.readI64();
              struct.setHeartbeatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REPLY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.reply_id = iprot.readString();
              struct.setReply_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SUBSCRIPTIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.subscriptions = new ArrayList<DigestSubscription>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  DigestSubscription _elem10;
                  _elem10 = new DigestSubscription();
                  _elem10.read(iprot);
                  struct.subscriptions.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setSubscriptionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetHeartbeat()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'heartbeat' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DigestSubscriptions struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HEARTBEAT_FIELD_DESC);
      oprot.writeI64(struct.heartbeat);
      oprot.writeFieldEnd();
      if (struct.reply_id != null) {
        oprot.writeFieldBegin(REPLY_ID_FIELD_DESC);
        oprot.writeString(struct.reply_id);
        oprot.writeFieldEnd();
      }
      if (struct.subscriptions != null) {
        oprot.writeFieldBegin(SUBSCRIPTIONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.subscriptions.size()));
          for (DigestSubscription _iter11 : struct.subscriptions)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DigestSubscriptionsTupleSchemeFactory implements SchemeFactory {
    public DigestSubscriptionsTupleScheme getScheme() {
      return new DigestSubscriptionsTupleScheme();
    }
  }

  private static class DigestSubscriptionsTupleScheme extends TupleScheme<DigestSubscriptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DigestSubscriptions struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.name);
      oprot.writeI64(struct.heartbeat);
      oprot.writeString(struct.reply_id);
      {
        oprot.writeI32(struct.subscriptions.size());
        for (DigestSubscription _iter12 : struct.subscriptions)
        {
          _iter12.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DigestSubscriptions struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.name = iprot.readString();
      struct.setNameIsSet(true);
      struct.heartbeat = iprot.readI64();
      struct.setHeartbeatIsSet(true);
      struct.reply_id = iprot.readString();
      struct.setReply_idIsSet(true);
      {
        org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.subscriptions = new ArrayList<DigestSubscription>(_list13.size);
        for (int _i14 = 0; _i14 < _list13.size; ++_i14)
        {
          DigestSubscription _elem15;
          _elem15 = new DigestSubscription();
          _elem15.read(iprot);
          struct.subscriptions.add(_elem15);
        }
      }
      struct.setSubscriptionsIsSet(true);
    }
  }

}

