/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gossiperl.client.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DigestError implements org.apache.thrift.TBase<DigestError, DigestError._Fields>, java.io.Serializable, Cloneable, Comparable<DigestError> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DigestError");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField HEARTBEAT_FIELD_DESC = new org.apache.thrift.protocol.TField("heartbeat", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField ERROR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("error_code", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField ERROR_ENTITY_FIELD_DESC = new org.apache.thrift.protocol.TField("error_entity", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField ERROR_ENTITY_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("error_entity_name", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField ERROR_MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("error_message", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField REPLY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("reply_id", org.apache.thrift.protocol.TType.STRING, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DigestErrorStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DigestErrorTupleSchemeFactory());
  }

  public String name; // required
  public long heartbeat; // required
  public int error_code; // required
  public String error_entity; // required
  public String error_entity_name; // required
  public String error_message; // required
  public String reply_id; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    HEARTBEAT((short)2, "heartbeat"),
    ERROR_CODE((short)3, "error_code"),
    ERROR_ENTITY((short)4, "error_entity"),
    ERROR_ENTITY_NAME((short)5, "error_entity_name"),
    ERROR_MESSAGE((short)6, "error_message"),
    REPLY_ID((short)7, "reply_id");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // HEARTBEAT
          return HEARTBEAT;
        case 3: // ERROR_CODE
          return ERROR_CODE;
        case 4: // ERROR_ENTITY
          return ERROR_ENTITY;
        case 5: // ERROR_ENTITY_NAME
          return ERROR_ENTITY_NAME;
        case 6: // ERROR_MESSAGE
          return ERROR_MESSAGE;
        case 7: // REPLY_ID
          return REPLY_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HEARTBEAT_ISSET_ID = 0;
  private static final int __ERROR_CODE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HEARTBEAT, new org.apache.thrift.meta_data.FieldMetaData("heartbeat", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ERROR_CODE, new org.apache.thrift.meta_data.FieldMetaData("error_code", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ERROR_ENTITY, new org.apache.thrift.meta_data.FieldMetaData("error_entity", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ERROR_ENTITY_NAME, new org.apache.thrift.meta_data.FieldMetaData("error_entity_name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ERROR_MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("error_message", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REPLY_ID, new org.apache.thrift.meta_data.FieldMetaData("reply_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DigestError.class, metaDataMap);
  }

  public DigestError() {
  }

  public DigestError(
    String name,
    long heartbeat,
    int error_code,
    String error_entity,
    String error_entity_name,
    String error_message,
    String reply_id)
  {
    this();
    this.name = name;
    this.heartbeat = heartbeat;
    setHeartbeatIsSet(true);
    this.error_code = error_code;
    setError_codeIsSet(true);
    this.error_entity = error_entity;
    this.error_entity_name = error_entity_name;
    this.error_message = error_message;
    this.reply_id = reply_id;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DigestError(DigestError other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetName()) {
      this.name = other.name;
    }
    this.heartbeat = other.heartbeat;
    this.error_code = other.error_code;
    if (other.isSetError_entity()) {
      this.error_entity = other.error_entity;
    }
    if (other.isSetError_entity_name()) {
      this.error_entity_name = other.error_entity_name;
    }
    if (other.isSetError_message()) {
      this.error_message = other.error_message;
    }
    if (other.isSetReply_id()) {
      this.reply_id = other.reply_id;
    }
  }

  public DigestError deepCopy() {
    return new DigestError(this);
  }

  @Override
  public void clear() {
    this.name = null;
    setHeartbeatIsSet(false);
    this.heartbeat = 0;
    setError_codeIsSet(false);
    this.error_code = 0;
    this.error_entity = null;
    this.error_entity_name = null;
    this.error_message = null;
    this.reply_id = null;
  }

  public String getName() {
    return this.name;
  }

  public DigestError setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public long getHeartbeat() {
    return this.heartbeat;
  }

  public DigestError setHeartbeat(long heartbeat) {
    this.heartbeat = heartbeat;
    setHeartbeatIsSet(true);
    return this;
  }

  public void unsetHeartbeat() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HEARTBEAT_ISSET_ID);
  }

  /** Returns true if field heartbeat is set (has been assigned a value) and false otherwise */
  public boolean isSetHeartbeat() {
    return EncodingUtils.testBit(__isset_bitfield, __HEARTBEAT_ISSET_ID);
  }

  public void setHeartbeatIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HEARTBEAT_ISSET_ID, value);
  }

  public int getError_code() {
    return this.error_code;
  }

  public DigestError setError_code(int error_code) {
    this.error_code = error_code;
    setError_codeIsSet(true);
    return this;
  }

  public void unsetError_code() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ERROR_CODE_ISSET_ID);
  }

  /** Returns true if field error_code is set (has been assigned a value) and false otherwise */
  public boolean isSetError_code() {
    return EncodingUtils.testBit(__isset_bitfield, __ERROR_CODE_ISSET_ID);
  }

  public void setError_codeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ERROR_CODE_ISSET_ID, value);
  }

  public String getError_entity() {
    return this.error_entity;
  }

  public DigestError setError_entity(String error_entity) {
    this.error_entity = error_entity;
    return this;
  }

  public void unsetError_entity() {
    this.error_entity = null;
  }

  /** Returns true if field error_entity is set (has been assigned a value) and false otherwise */
  public boolean isSetError_entity() {
    return this.error_entity != null;
  }

  public void setError_entityIsSet(boolean value) {
    if (!value) {
      this.error_entity = null;
    }
  }

  public String getError_entity_name() {
    return this.error_entity_name;
  }

  public DigestError setError_entity_name(String error_entity_name) {
    this.error_entity_name = error_entity_name;
    return this;
  }

  public void unsetError_entity_name() {
    this.error_entity_name = null;
  }

  /** Returns true if field error_entity_name is set (has been assigned a value) and false otherwise */
  public boolean isSetError_entity_name() {
    return this.error_entity_name != null;
  }

  public void setError_entity_nameIsSet(boolean value) {
    if (!value) {
      this.error_entity_name = null;
    }
  }

  public String getError_message() {
    return this.error_message;
  }

  public DigestError setError_message(String error_message) {
    this.error_message = error_message;
    return this;
  }

  public void unsetError_message() {
    this.error_message = null;
  }

  /** Returns true if field error_message is set (has been assigned a value) and false otherwise */
  public boolean isSetError_message() {
    return this.error_message != null;
  }

  public void setError_messageIsSet(boolean value) {
    if (!value) {
      this.error_message = null;
    }
  }

  public String getReply_id() {
    return this.reply_id;
  }

  public DigestError setReply_id(String reply_id) {
    this.reply_id = reply_id;
    return this;
  }

  public void unsetReply_id() {
    this.reply_id = null;
  }

  /** Returns true if field reply_id is set (has been assigned a value) and false otherwise */
  public boolean isSetReply_id() {
    return this.reply_id != null;
  }

  public void setReply_idIsSet(boolean value) {
    if (!value) {
      this.reply_id = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case HEARTBEAT:
      if (value == null) {
        unsetHeartbeat();
      } else {
        setHeartbeat((Long)value);
      }
      break;

    case ERROR_CODE:
      if (value == null) {
        unsetError_code();
      } else {
        setError_code((Integer)value);
      }
      break;

    case ERROR_ENTITY:
      if (value == null) {
        unsetError_entity();
      } else {
        setError_entity((String)value);
      }
      break;

    case ERROR_ENTITY_NAME:
      if (value == null) {
        unsetError_entity_name();
      } else {
        setError_entity_name((String)value);
      }
      break;

    case ERROR_MESSAGE:
      if (value == null) {
        unsetError_message();
      } else {
        setError_message((String)value);
      }
      break;

    case REPLY_ID:
      if (value == null) {
        unsetReply_id();
      } else {
        setReply_id((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case HEARTBEAT:
      return Long.valueOf(getHeartbeat());

    case ERROR_CODE:
      return Integer.valueOf(getError_code());

    case ERROR_ENTITY:
      return getError_entity();

    case ERROR_ENTITY_NAME:
      return getError_entity_name();

    case ERROR_MESSAGE:
      return getError_message();

    case REPLY_ID:
      return getReply_id();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case HEARTBEAT:
      return isSetHeartbeat();
    case ERROR_CODE:
      return isSetError_code();
    case ERROR_ENTITY:
      return isSetError_entity();
    case ERROR_ENTITY_NAME:
      return isSetError_entity_name();
    case ERROR_MESSAGE:
      return isSetError_message();
    case REPLY_ID:
      return isSetReply_id();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DigestError)
      return this.equals((DigestError)that);
    return false;
  }

  public boolean equals(DigestError that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_heartbeat = true;
    boolean that_present_heartbeat = true;
    if (this_present_heartbeat || that_present_heartbeat) {
      if (!(this_present_heartbeat && that_present_heartbeat))
        return false;
      if (this.heartbeat != that.heartbeat)
        return false;
    }

    boolean this_present_error_code = true;
    boolean that_present_error_code = true;
    if (this_present_error_code || that_present_error_code) {
      if (!(this_present_error_code && that_present_error_code))
        return false;
      if (this.error_code != that.error_code)
        return false;
    }

    boolean this_present_error_entity = true && this.isSetError_entity();
    boolean that_present_error_entity = true && that.isSetError_entity();
    if (this_present_error_entity || that_present_error_entity) {
      if (!(this_present_error_entity && that_present_error_entity))
        return false;
      if (!this.error_entity.equals(that.error_entity))
        return false;
    }

    boolean this_present_error_entity_name = true && this.isSetError_entity_name();
    boolean that_present_error_entity_name = true && that.isSetError_entity_name();
    if (this_present_error_entity_name || that_present_error_entity_name) {
      if (!(this_present_error_entity_name && that_present_error_entity_name))
        return false;
      if (!this.error_entity_name.equals(that.error_entity_name))
        return false;
    }

    boolean this_present_error_message = true && this.isSetError_message();
    boolean that_present_error_message = true && that.isSetError_message();
    if (this_present_error_message || that_present_error_message) {
      if (!(this_present_error_message && that_present_error_message))
        return false;
      if (!this.error_message.equals(that.error_message))
        return false;
    }

    boolean this_present_reply_id = true && this.isSetReply_id();
    boolean that_present_reply_id = true && that.isSetReply_id();
    if (this_present_reply_id || that_present_reply_id) {
      if (!(this_present_reply_id && that_present_reply_id))
        return false;
      if (!this.reply_id.equals(that.reply_id))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(DigestError other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHeartbeat()).compareTo(other.isSetHeartbeat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHeartbeat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.heartbeat, other.heartbeat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetError_code()).compareTo(other.isSetError_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error_code, other.error_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetError_entity()).compareTo(other.isSetError_entity());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError_entity()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error_entity, other.error_entity);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetError_entity_name()).compareTo(other.isSetError_entity_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError_entity_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error_entity_name, other.error_entity_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetError_message()).compareTo(other.isSetError_message());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError_message()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error_message, other.error_message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReply_id()).compareTo(other.isSetReply_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReply_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reply_id, other.reply_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DigestError(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("heartbeat:");
    sb.append(this.heartbeat);
    first = false;
    if (!first) sb.append(", ");
    sb.append("error_code:");
    sb.append(this.error_code);
    first = false;
    if (!first) sb.append(", ");
    sb.append("error_entity:");
    if (this.error_entity == null) {
      sb.append("null");
    } else {
      sb.append(this.error_entity);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("error_entity_name:");
    if (this.error_entity_name == null) {
      sb.append("null");
    } else {
      sb.append(this.error_entity_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("error_message:");
    if (this.error_message == null) {
      sb.append("null");
    } else {
      sb.append(this.error_message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("reply_id:");
    if (this.reply_id == null) {
      sb.append("null");
    } else {
      sb.append(this.reply_id);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'name' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'heartbeat' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'error_code' because it's a primitive and you chose the non-beans generator.
    if (error_entity == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'error_entity' was not present! Struct: " + toString());
    }
    if (error_entity_name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'error_entity_name' was not present! Struct: " + toString());
    }
    if (error_message == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'error_message' was not present! Struct: " + toString());
    }
    if (reply_id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'reply_id' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DigestErrorStandardSchemeFactory implements SchemeFactory {
    public DigestErrorStandardScheme getScheme() {
      return new DigestErrorStandardScheme();
    }
  }

  private static class DigestErrorStandardScheme extends StandardScheme<DigestError> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DigestError struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HEARTBEAT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.heartbeat = iprot.readI64();
              struct.setHeartbeatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ERROR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.error_code = iprot.readI32();
              struct.setError_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ERROR_ENTITY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error_entity = iprot.readString();
              struct.setError_entityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ERROR_ENTITY_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error_entity_name = iprot.readString();
              struct.setError_entity_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ERROR_MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error_message = iprot.readString();
              struct.setError_messageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // REPLY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.reply_id = iprot.readString();
              struct.setReply_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetHeartbeat()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'heartbeat' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetError_code()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'error_code' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DigestError struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HEARTBEAT_FIELD_DESC);
      oprot.writeI64(struct.heartbeat);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
      oprot.writeI32(struct.error_code);
      oprot.writeFieldEnd();
      if (struct.error_entity != null) {
        oprot.writeFieldBegin(ERROR_ENTITY_FIELD_DESC);
        oprot.writeString(struct.error_entity);
        oprot.writeFieldEnd();
      }
      if (struct.error_entity_name != null) {
        oprot.writeFieldBegin(ERROR_ENTITY_NAME_FIELD_DESC);
        oprot.writeString(struct.error_entity_name);
        oprot.writeFieldEnd();
      }
      if (struct.error_message != null) {
        oprot.writeFieldBegin(ERROR_MESSAGE_FIELD_DESC);
        oprot.writeString(struct.error_message);
        oprot.writeFieldEnd();
      }
      if (struct.reply_id != null) {
        oprot.writeFieldBegin(REPLY_ID_FIELD_DESC);
        oprot.writeString(struct.reply_id);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DigestErrorTupleSchemeFactory implements SchemeFactory {
    public DigestErrorTupleScheme getScheme() {
      return new DigestErrorTupleScheme();
    }
  }

  private static class DigestErrorTupleScheme extends TupleScheme<DigestError> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DigestError struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.name);
      oprot.writeI64(struct.heartbeat);
      oprot.writeI32(struct.error_code);
      oprot.writeString(struct.error_entity);
      oprot.writeString(struct.error_entity_name);
      oprot.writeString(struct.error_message);
      oprot.writeString(struct.reply_id);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DigestError struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.name = iprot.readString();
      struct.setNameIsSet(true);
      struct.heartbeat = iprot.readI64();
      struct.setHeartbeatIsSet(true);
      struct.error_code = iprot.readI32();
      struct.setError_codeIsSet(true);
      struct.error_entity = iprot.readString();
      struct.setError_entityIsSet(true);
      struct.error_entity_name = iprot.readString();
      struct.setError_entity_nameIsSet(true);
      struct.error_message = iprot.readString();
      struct.setError_messageIsSet(true);
      struct.reply_id = iprot.readString();
      struct.setReply_idIsSet(true);
    }
  }

}

