/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gossiperl.client.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DigestEvent implements org.apache.thrift.TBase<DigestEvent, DigestEvent._Fields>, java.io.Serializable, Cloneable, Comparable<DigestEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DigestEvent");

  private static final org.apache.thrift.protocol.TField EVENT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("event_type", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField EVENT_OBJECT_FIELD_DESC = new org.apache.thrift.protocol.TField("event_object", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField HEARTBEAT_FIELD_DESC = new org.apache.thrift.protocol.TField("heartbeat", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DigestEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DigestEventTupleSchemeFactory());
  }

  public String event_type; // required
  public String event_object; // required
  public long heartbeat; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EVENT_TYPE((short)1, "event_type"),
    EVENT_OBJECT((short)2, "event_object"),
    HEARTBEAT((short)3, "heartbeat");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EVENT_TYPE
          return EVENT_TYPE;
        case 2: // EVENT_OBJECT
          return EVENT_OBJECT;
        case 3: // HEARTBEAT
          return HEARTBEAT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HEARTBEAT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EVENT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("event_type", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EVENT_OBJECT, new org.apache.thrift.meta_data.FieldMetaData("event_object", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HEARTBEAT, new org.apache.thrift.meta_data.FieldMetaData("heartbeat", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DigestEvent.class, metaDataMap);
  }

  public DigestEvent() {
  }

  public DigestEvent(
    String event_type,
    String event_object,
    long heartbeat)
  {
    this();
    this.event_type = event_type;
    this.event_object = event_object;
    this.heartbeat = heartbeat;
    setHeartbeatIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DigestEvent(DigestEvent other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetEvent_type()) {
      this.event_type = other.event_type;
    }
    if (other.isSetEvent_object()) {
      this.event_object = other.event_object;
    }
    this.heartbeat = other.heartbeat;
  }

  public DigestEvent deepCopy() {
    return new DigestEvent(this);
  }

  @Override
  public void clear() {
    this.event_type = null;
    this.event_object = null;
    setHeartbeatIsSet(false);
    this.heartbeat = 0;
  }

  public String getEvent_type() {
    return this.event_type;
  }

  public DigestEvent setEvent_type(String event_type) {
    this.event_type = event_type;
    return this;
  }

  public void unsetEvent_type() {
    this.event_type = null;
  }

  /** Returns true if field event_type is set (has been assigned a value) and false otherwise */
  public boolean isSetEvent_type() {
    return this.event_type != null;
  }

  public void setEvent_typeIsSet(boolean value) {
    if (!value) {
      this.event_type = null;
    }
  }

  public String getEvent_object() {
    return this.event_object;
  }

  public DigestEvent setEvent_object(String event_object) {
    this.event_object = event_object;
    return this;
  }

  public void unsetEvent_object() {
    this.event_object = null;
  }

  /** Returns true if field event_object is set (has been assigned a value) and false otherwise */
  public boolean isSetEvent_object() {
    return this.event_object != null;
  }

  public void setEvent_objectIsSet(boolean value) {
    if (!value) {
      this.event_object = null;
    }
  }

  public long getHeartbeat() {
    return this.heartbeat;
  }

  public DigestEvent setHeartbeat(long heartbeat) {
    this.heartbeat = heartbeat;
    setHeartbeatIsSet(true);
    return this;
  }

  public void unsetHeartbeat() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HEARTBEAT_ISSET_ID);
  }

  /** Returns true if field heartbeat is set (has been assigned a value) and false otherwise */
  public boolean isSetHeartbeat() {
    return EncodingUtils.testBit(__isset_bitfield, __HEARTBEAT_ISSET_ID);
  }

  public void setHeartbeatIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HEARTBEAT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EVENT_TYPE:
      if (value == null) {
        unsetEvent_type();
      } else {
        setEvent_type((String)value);
      }
      break;

    case EVENT_OBJECT:
      if (value == null) {
        unsetEvent_object();
      } else {
        setEvent_object((String)value);
      }
      break;

    case HEARTBEAT:
      if (value == null) {
        unsetHeartbeat();
      } else {
        setHeartbeat((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EVENT_TYPE:
      return getEvent_type();

    case EVENT_OBJECT:
      return getEvent_object();

    case HEARTBEAT:
      return Long.valueOf(getHeartbeat());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EVENT_TYPE:
      return isSetEvent_type();
    case EVENT_OBJECT:
      return isSetEvent_object();
    case HEARTBEAT:
      return isSetHeartbeat();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DigestEvent)
      return this.equals((DigestEvent)that);
    return false;
  }

  public boolean equals(DigestEvent that) {
    if (that == null)
      return false;

    boolean this_present_event_type = true && this.isSetEvent_type();
    boolean that_present_event_type = true && that.isSetEvent_type();
    if (this_present_event_type || that_present_event_type) {
      if (!(this_present_event_type && that_present_event_type))
        return false;
      if (!this.event_type.equals(that.event_type))
        return false;
    }

    boolean this_present_event_object = true && this.isSetEvent_object();
    boolean that_present_event_object = true && that.isSetEvent_object();
    if (this_present_event_object || that_present_event_object) {
      if (!(this_present_event_object && that_present_event_object))
        return false;
      if (!this.event_object.equals(that.event_object))
        return false;
    }

    boolean this_present_heartbeat = true;
    boolean that_present_heartbeat = true;
    if (this_present_heartbeat || that_present_heartbeat) {
      if (!(this_present_heartbeat && that_present_heartbeat))
        return false;
      if (this.heartbeat != that.heartbeat)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(DigestEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEvent_type()).compareTo(other.isSetEvent_type());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEvent_type()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.event_type, other.event_type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEvent_object()).compareTo(other.isSetEvent_object());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEvent_object()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.event_object, other.event_object);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHeartbeat()).compareTo(other.isSetHeartbeat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHeartbeat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.heartbeat, other.heartbeat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DigestEvent(");
    boolean first = true;

    sb.append("event_type:");
    if (this.event_type == null) {
      sb.append("null");
    } else {
      sb.append(this.event_type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("event_object:");
    if (this.event_object == null) {
      sb.append("null");
    } else {
      sb.append(this.event_object);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("heartbeat:");
    sb.append(this.heartbeat);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (event_type == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'event_type' was not present! Struct: " + toString());
    }
    if (event_object == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'event_object' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'heartbeat' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DigestEventStandardSchemeFactory implements SchemeFactory {
    public DigestEventStandardScheme getScheme() {
      return new DigestEventStandardScheme();
    }
  }

  private static class DigestEventStandardScheme extends StandardScheme<DigestEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DigestEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EVENT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.event_type = iprot.readString();
              struct.setEvent_typeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EVENT_OBJECT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.event_object = iprot.readString();
              struct.setEvent_objectIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // HEARTBEAT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.heartbeat = iprot.readI64();
              struct.setHeartbeatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetHeartbeat()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'heartbeat' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DigestEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.event_type != null) {
        oprot.writeFieldBegin(EVENT_TYPE_FIELD_DESC);
        oprot.writeString(struct.event_type);
        oprot.writeFieldEnd();
      }
      if (struct.event_object != null) {
        oprot.writeFieldBegin(EVENT_OBJECT_FIELD_DESC);
        oprot.writeString(struct.event_object);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HEARTBEAT_FIELD_DESC);
      oprot.writeI64(struct.heartbeat);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DigestEventTupleSchemeFactory implements SchemeFactory {
    public DigestEventTupleScheme getScheme() {
      return new DigestEventTupleScheme();
    }
  }

  private static class DigestEventTupleScheme extends TupleScheme<DigestEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DigestEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.event_type);
      oprot.writeString(struct.event_object);
      oprot.writeI64(struct.heartbeat);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DigestEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.event_type = iprot.readString();
      struct.setEvent_typeIsSet(true);
      struct.event_object = iprot.readString();
      struct.setEvent_objectIsSet(true);
      struct.heartbeat = iprot.readI64();
      struct.setHeartbeatIsSet(true);
    }
  }

}

